# Arithmetic operations

## addition, subtraction, multiplication, division

import numpy as np
a=np.arange(1,5)
b=np.arange(2,6)
print("array a:",a)
print("array b:",b)

#one type
print(a*4)

#second type
print("add:",np.add(a,b))
print("sub:",np.subtract(b,a))
print("mul:",np.multiply(a,b))
print("div:",np.divide(b,a))


In [3]:
c=np.arange(0,9).reshape(3,3)
d=np.ones((3,3))
d=d+3
c+d

array([[ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]])

# Functions

## reciprocal() method

In [8]:
np.reciprocal(d)

array([[0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25],
       [0.25, 0.25, 0.25]])

## power() method

In [10]:
np.power(a,2)

array([ 1,  4,  9, 16], dtype=int32)

## mod() method

In [11]:
np.mod(c,d)

array([[0., 1., 2.],
       [3., 0., 1.],
       [2., 3., 0.]])