# Testing the installation

In [2]:
import numpy as np


# create an array

In [3]:

#one dimensional array
a = np.array([1,2,3,4])
print("one dimensional array:\n",a)

# two dimensional array
b = np.array([[1,2,3],[5,4,3],[6,7,4]])
print("two dimensional array:\n",b)

one dimensional array:
 [1 2 3 4]
two dimensional array:
 [[1 2 3]
 [5 4 3]
 [6 7 4]]


# create array with Data type option

In [4]:
c = np.array([[5,4,-3],[2,4,0]],dtype=bool)
c

array([[ True,  True,  True],
       [ True,  True, False]])

 # Intrinsic creation of array
 
## single line of code to generate large amounts of data 

## by default below two functions created array with float64 data type


## zeros() funcion

In [38]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# ones() funcion

In [39]:
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# arange() function 1D array

In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(3,7)

array([3, 4, 5, 6])

In [44]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])


# arange() function 2D array with reshape() functoin

In [6]:
np.arange(0,12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# linspace() function

### first two arguments takes as initial and end value of sequence and third argument as split the distance


In [56]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# random() function

In [59]:
np.random.random((2,3))

array([[0.63403955, 0.10757966, 0.10241275],
       [0.50277694, 0.5793173 , 0.45892887]])