# The matrix product

## The dot() function


In [3]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
b=np.ones((3,3))

# one method
np.dot(a,b)

# second method
a.dot(b)

array([[ 3.,  3.,  3.],
       [12., 12., 12.],
       [21., 21., 21.]])

# Increment operators

In [5]:
c=np.arange(4)
c+=3
c

array([3, 4, 5, 6])

# Decrement operators

In [6]:
d=np.arange(3,7)
d-=2
d

array([1, 2, 3, 4])