In [1]:
import numpy as np 

In [3]:
arr = np.array([[1,3],[4,5]])
arr

array([[1, 3],
       [4, 5]])

In [7]:
print(type(arr))
print(arr.shape)
print(arr.size)

<class 'numpy.ndarray'>
(2, 2)
4


In [12]:
a=np.zeros([3,3])
b=np.ones([3,4])
c=np.random.random([4,4])
print(a)
print(b)
print(c)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0.98441961 0.99952293 0.63203439 0.34308531]
 [0.15922782 0.91008342 0.09164463 0.93220734]
 [0.91198731 0.46428945 0.22817271 0.13138871]
 [0.08371836 0.0928252  0.03435499 0.07836076]]


In [15]:
ar = np.full((4,4),6)
print(ar)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [17]:
ar.reshape(2,2,4)

array([[[6, 6, 6, 6],
        [6, 6, 6, 6]],

       [[6, 6, 6, 6],
        [6, 6, 6, 6]]])

In [20]:
ar.flatten()

array([6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [22]:
# unary operator
print(arr.min())
print(arr.max())
print(arr.sum())

1
5
13


In [24]:
# Binary operator
c1 = np.array([[3,4],[6,7]])
c2 = np.array([[2,6],[5,3]])

print(c1*c2)
print(c1+c2)
print(c1.dot(c2))

[[ 6 24]
 [30 21]]
[[ 5 10]
 [11 10]]
[[26 30]
 [47 57]]


In [26]:
# matmul
np.matmul(c1,c2)

array([[26, 30],
       [47, 57]])

In [30]:
#sorting
c3 = np.random.random((3,4))
print( np.sort(c3, axis=0 ))
print( np.sort(c3, axis=1 ))

[[0.66704443 0.09301394 0.07601723 0.49751741]
 [0.77619161 0.29880359 0.5636306  0.74100247]
 [0.85856262 0.90068082 0.7426558  0.8358536 ]]
[[0.29880359 0.49751741 0.7426558  0.77619161]
 [0.09301394 0.5636306  0.66704443 0.8358536 ]
 [0.07601723 0.74100247 0.85856262 0.90068082]]
