In [2]:
import tensorflow as tf 
print(tf.__version__)

2.0.0


In [9]:
# Declaring Eager vriable
v0 = 33
v1 = tf.Variable(54)
v2 = tf.Variable([1,2])
v3 = tf.Variable([3,2],[6,7])

print(v0)
print(v1)
print(v2)
print(v3)

33
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=54>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 2])>


In [7]:
# Reassign
v1.assign(21)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=21>

In [10]:
# Declaring Tensorflow constants
c1 = tf.constant(36)
c2 = tf.constant(62, dtype=tf.float64)

print(c1,"\n",c2)

tf.Tensor(36, shape=(), dtype=int32) 
 tf.Tensor(62.0, shape=(), dtype=float64)


In [19]:
# shaping tensors
t1 = tf.Variable([[3,4,2],[6,1,9]])
t1.shape

TensorShape([2, 3])

In [20]:
t2 = tf.reshape(t1, [1,6])
t2.shape

TensorShape([1, 6])

In [21]:
# Ranking(diemnsions) of a tensors
tf.rank(t1)

<tf.Tensor: id=186, shape=(), dtype=int32, numpy=2>

In [23]:
# specifying and element of a tensor
t3 = t2[0,1]
t3

<tf.Tensor: id=194, shape=(), dtype=int32, numpy=4>

In [24]:
# casting tensor to  numpy
t3.numpy()

4

In [27]:
# finding the number of element in tensor
tf.size(input=t2).numpy()


6

In [28]:
# finding data typr
t3.dtype

tf.int32

In [43]:
# operator
a1 = tf.Variable([1,3])
a2 = tf.Variable([3,6])

(a1+a2).numpy()

array([4, 9])

In [38]:
# matrix
c3 = tf.constant([[2,4],[3,1]])
c4 = tf.constant([[5,9],[7,4]])
tf.matmul(c3,c4).numpy()

array([[38, 34],
       [22, 31]])

In [41]:
# type casting
c5 = tf.cast(c3, dtype=tf.float64)
c5

<tf.Tensor: id=312, shape=(2, 2), dtype=float64, numpy=
array([[2., 4.],
       [3., 1.]])>

In [42]:
# declaring ragged tensors
rag = tf.ragged.constant([[1],[],[3,6,1],[7,8]])
rag

<tf.RaggedTensor [[1], [], [3, 6, 1], [7, 8]]>

In [47]:
# tensorflow operation
v1 = tf.Variable([3,4])
v2 = tf.Variable([2,2])
tf.math.squared_difference(v1, v2, name=None).numpy()

array([1, 4])

In [48]:
tf.reduce_mean(v1)

<tf.Tensor: id=431, shape=(), dtype=int32, numpy=3>

In [50]:
tf.reduce_mean(v3, axis=0)

<tf.Tensor: id=434, shape=(), dtype=int32, numpy=2>

In [52]:
# generating tensors with random values
tf.random.normal(shape=(3,2), mean=10, stddev=2, dtype=tf.float32)


<tf.Tensor: id=440, shape=(3, 2), dtype=float32, numpy=
array([[ 7.721836,  7.927163],
       [13.472234,  8.81576 ],
       [ 9.764047,  9.598276]], dtype=float32)>

In [53]:
tf.random.uniform(shape=(3,2), minval=0, maxval=5, dtype=tf.int32)

<tf.Tensor: id=444, shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 2],
       [0, 1]])>

In [55]:
tf.random.set_seed(111)
tf.random.uniform(shape=(3,3), maxval=6)

<tf.Tensor: id=458, shape=(3, 3), dtype=float32, numpy=
array([[1.3675804 , 0.43453074, 1.5543015 ],
       [1.6157205 , 5.9757886 , 1.3171234 ],
       [1.1493652 , 4.5679765 , 5.349658  ]], dtype=float32)>

In [57]:
# concatenate two tensors
b1 = tf.concat(values=[v1,v2], axis=0)
b1

<tf.Tensor: id=472, shape=(4,), dtype=int32, numpy=array([3, 4, 2, 2])>

In [64]:
# min max 
tf.argmax(input=b1).numpy()
# it given only index value

1

In [65]:
tf.argmin(input=b1)

<tf.Tensor: id=486, shape=(), dtype=int64, numpy=2>

In [67]:
#saving and restoring tensor values using a checkpoint

q1 = tf.Variable([[3,3],[4,1]])
check = tf.train.Checkpoint(var=q1)
save_path = check.save('./myvariable')
save_path

'./myvariable-1'

In [68]:
q1.assign([[0,0],[0,0]])
q1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 0],
       [0, 0]])>

In [71]:
check.restore(save_path)
q1

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[3, 3],
       [4, 1]])>